# Generated by Django 4.0.3 on 2022-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders_admin', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=20)),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
            ],
        ),
    ]
